#!/usr/bin/env python3
"""Extract the IAU 2000A and NU2000K nutation coefficient tables from the legacy
NOVAS-C nutation.c into a C++ include file.

These tables are the standard IAU nutation series (Kaplan 2005, USNO Circular
179), not NOVAS-specific code, so transcribing the numbers is appropriate. We
extract rather than hand-copy to avoid transcription error; the result
(src/nutation_tables.inc) is committed as library source because nutation.c is
a fetched artifact not present at build time.

Usage:
  tools/extract_nutation_tables.py <path/to/nutation.c> <out.inc>
"""
import re
import sys


def capture_initializer(text, start):
    """Return the brace-balanced initializer '{...}' beginning at or after
    index `start`, and the index just past its closing brace."""
    i = text.index("{", start)
    depth = 0
    j = i
    while j < len(text):
        c = text[j]
        if c == "{":
            depth += 1
        elif c == "}":
            depth -= 1
            if depth == 0:
                return text[i : j + 1], j + 1
        j += 1
    raise ValueError("unbalanced braces")


# (source array declaration, emitted C++ name, element type)
TARGETS = [
    # IAU 2000A (accuracy = full): 678 luni-solar + 687 planetary terms.
    (r"short int\s+nals_t\[678\]\[5\]\s*=", "nals_a", "int"),
    (r"double\s+cls_t\[678\]\[6\]\s*=", "cls_a", "double"),
    (r"short int\s+napl_t\[687\]\[14\]\s*=", "napl_a", "int"),
    (r"double\s+cpl_t\[687\]\[4\]\s*=", "cpl_a", "double"),
    # NU2000K (accuracy = reduced): 323 luni-solar + 165 planetary terms.
    (r"short int\s+nals_t\[323\]\[5\]\s*=", "nals_k", "int"),
    (r"double\s+cls_t\[323\]\[6\]\s*=", "cls_k", "double"),
    (r"short int\s+napl_t\[165\]\[14\]\s*=", "napl_k", "int"),
    (r"double\s+cpl_t\[165\]\[4\]\s*=", "cpl_k", "double"),
]


def main():
    if len(sys.argv) != 3:
        sys.exit("usage: extract_nutation_tables.py <nutation.c> <out.inc>")
    src = open(sys.argv[1]).read()

    out = [
        "// AUTO-GENERATED by tools/extract_nutation_tables.py from",
        "// novasc3.1/nutation.c -- do not edit by hand.",
        "//",
        "// IAU 2000A / NU2000K nutation series (Kaplan 2005, USNO Circular 179).",
        "",
    ]
    pos = 0
    for pattern, name, etype in TARGETS:
        m = re.search(pattern, src[pos:])
        if not m:
            sys.exit(f"declaration not found: {pattern}")
        decl_at = pos + m.start()
        init, end = capture_initializer(src, decl_at)
        pos = end
        dims = re.search(r"\[(\d+)\]\[(\d+)\]", m.group(0))
        n, k = dims.group(1), dims.group(2)
        out.append(f"static const {etype} {name}[{n}][{k}] = {init};")
        out.append("")

    open(sys.argv[2], "w").write("\n".join(out))
    print(f"wrote {sys.argv[2]}")


if __name__ == "__main__":
    main()
